version: '3.0'

services:
  registry:
    container_name: docker-registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /home/registry/docker-registry-data:/var/lib/registry
