- hosts: gitServer
  become: true
  tasks:

    - name: Create /home/gitlab directory
      file: 
        path: /home/gitlab
        state: directory
        mode: 0775

    - name: Copy docker compose file to host
      copy:
        src: /etc/ansible/gitlab/docker-compose.yml
        dest: /home/gitlab/docker-compose.yml

    - name: Creating gitlab with docker-compose
      shell: "docker-compose -f /home/gitlab/docker-compose.yml up -d"
      register: docker_compose_output

    - debug:
        msg: "Creating docker-compose result: {{docker_compose_output.stdout}}"

    - name: Control gitlab container
      shell: "docker ps -f name=gitlab"
      register: control_docker

    - debug:
        msg: "{{control_docker.stdout}}"
