web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  container_name: gitlab
  hostname: localhost
  ports:
    - '80:80'
    - '443:443'
    - '22:22'
  volumes:
    - '/home/gitlab/volumes/config:/etc/gitlab'
    - '/home/gitlab/volumes/logs:/var/log/gitlab'
    - '/home/gitlab/volumes/data:/var/opt/gitlab'
